### ISSUE TITLE
Unexpected token ) at build.js

### ISSUE THREAD

**Issue by soullivaneuh** [Flood-UI/flood#816]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.
- [x] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [x] Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

## Your Environment

* Version used:
  + Version (stable release) `v1.0.0`
  + Commit ID (development release) `89934ab615d83d72b3db3d46e231e6a5c52f827a`
* Environment name and version:
  + Node.js version `v6.17.1`
  + npm version `3.10.10`
  + Web browser `Not revelant`
* Operating System and version:

```
Linux dediseed 4.4.0-91-generic #114-Ubuntu SMP Tue Aug 8 11:56:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

## Summary

Syntax error on build:

```
 npm run build


> flood@1.0.0 build /home/seedbox/flood
> node client/scripts/build.js

/home/seedbox/flood/client/scripts/build.js:64
          ),
          ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

npm ERR! Linux 4.4.0-91-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! flood@1.0.0 build: `node client/scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flood@1.0.0 build script 'node client/scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the flood package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node client/scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs flood
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls flood
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/seedbox/flood/npm-debug.log
```

1. Follow the upgrade guide
2. It should crash at `npm run build`

**Comment by soullivaneuh** [comment]
Ok it was a wrong version of nodejs, my bad. Sorry for that.
