### ISSUE TITLE
RangeError when trying to connect to flood (Docker with SSL)

### ISSUE THREAD

**Issue by robinwils** [Flood-UI/flood#827]
Type: Bug Report

## Your Environment

* Version used:
  + Version (stable release) `v1.0.0`
  + Commit ID (development release) `344a148cff5c79ea866ba7bfa7623212ff91aced`
* Environment name and version:
  + Docker version
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
  + Web browser `Firefox Quantum 68.0.2`
* Operating System and version:
`CentOS Linux release 7.6.1810 (Core) `
`Linux 3.10.0-327.36.2.el7.x86_64 #1 SMP Mon Oct 10 23:08:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

## Summary
I have been using flood with `docker` for some years now, first without SSL and since a few months with SSL. Everything was working fine, except I had to restart the container from time to time (that's another issue though).

A few weeks ago I got a RangeError from node when trying to restart the docker container.

## Expected Behavior
Everything runs fine

## Current Behavior

```

> flood@1.0.0 start /usr/src/app
> node --use_strict server/bin/start.js

Flood server starting on https://0.0.0.0:3000.

internal/buffer.js:941
class FastBuffer extends Uint8Array {}
^

RangeError: Invalid typed array length: -4095
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:941:1)
    at Handle.onStreamRead [as onread] (internal/stream_base_commons.js:165:17)
    at Stream.<anonymous> (/usr/src/app/node_modules/handle-thing/lib/handle.js:120:12)
    at Stream.emit (events.js:201:15)
    at endReadableNT (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flood@1.0.0 start: `node --use_strict server/bin/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flood@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-07T09_35_36_149Z-debug.log
```

```
/usr/src/app # cat /root/.npm/_logs/2019-09-07T09_35_36_149Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.9.0
3 info using node@v12.2.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle flood@1.0.0~prestart: flood@1.0.0
6 info lifecycle flood@1.0.0~start: flood@1.0.0
7 verbose lifecycle flood@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle flood@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/src/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle flood@1.0.0~start: CWD: /usr/src/app
10 silly lifecycle flood@1.0.0~start: Args: [ '-c', 'node --use_strict server/bin/start.js' ]
11 silly lifecycle flood@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle flood@1.0.0~start: Failed to exec start script
13 verbose stack Error: flood@1.0.0 start: `node --use_strict server/bin/start.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:196:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:196:13)
13 verbose stack     at maybeClose (internal/child_process.js:1011:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)
14 verbose pkgid flood@1.0.0
15 verbose cwd /usr/src/app
16 verbose Linux 3.10.0-327.36.2.el7.x86_64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v12.2.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error flood@1.0.0 start: `node --use_strict server/bin/start.js`
22 error Exit status 1
23 error Failed at the flood@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

## Steps to Reproduce

1. `docker build -t rtorrent-flood .`
2. Copy key and cert to `/path/to/local/data/`
3.
```
docker run --name rtorrent-flood -v /path/to/local/data:/data  -p 3000:3000 -e FLOOD_ENABLE_SSL=true rtorrent-flood
```
I got my ssl key and cert up to date:
```
diff /path/to/local/data/flood_ssl.key  /etc/letsencrypt/live/mydomain/privkey.pem
diff /path/to/local/data/flood_ssl.cert  /etc/letsencrypt/live/mydomain/cert.pem
```
both return 0.

**Comment by magnusottosson** [comment]
I get the same issue when running standalone with ssl cert from letsenctrypt.
