### ISSUE TITLE
ELIFECYCLE error on "npm run build"

### ISSUE THREAD

**Issue by gerwalk** [Flood-UI/flood#850]
Type: Bug Report

## Your Environment

* Version used:
  + v1.0.0
  + Commit bb553506a86225811a965563af99bf8e39cc433f
* Environment name and version:
  + Node.js version **v13.2.0**
  + npm version **6.12.1**
* Operating System and version: Arch Linux (kernel 5.3.13-arch1-1)

## Summary
This happened when I tried to update the package after performing a system update, and my first thought was something got out of sync/corrupted, so I completely deleted my clone of the flood repo and tried a fresh install. Still occurs.

`npm ERR! code ELIFECYCLE`
`npm ERR! errno 1`
`npm ERR! flood@1.0.0 build: 'node client/scripts/build.js'`
`npm ERR! Exit status 1`
`npm ERR!`
`npm ERR! Failed at the flood@1.0.0 build script.`
`npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

`npm ERR! A complete log of this run can be found in:`
`npm ERR!     /home/flint/.npm/_logs/2019-11-26T16_57_43_846Z-debug.log`

**/home/flint/.npm/_logs/2019-11-26T16_57_43_846Z-debug.log:**
`0 info it worked if it ends with ok`
`1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]`
`2 info using npm@6.12.1`
`3 info using node@v13.2.0`
`4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]`
`5 info lifecycle flood@1.0.0~prebuild: flood@1.0.0`
`6 info lifecycle flood@1.0.0~build: flood@1.0.0`
`7 verbose lifecycle flood@1.0.0~build: unsafe-perm in lifecycle true`
`8 verbose lifecycle flood@1.0.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/flint/flood/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
`9 verbose lifecycle flood@1.0.0~build: CWD: /home/flint/flood`
`10 silly lifecycle flood@1.0.0~build: Args: [ '-c', 'node client/scripts/build.js' ]`
`11 silly lifecycle flood@1.0.0~build: Returned: code: 1  signal: null`
`12 info lifecycle flood@1.0.0~build: Failed to exec build script`
`13 verbose stack Error: flood@1.0.0 build: 'node client/scripts/build.js'`
`13 verbose stack Exit status 1`
`13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)`
`13 verbose stack     at EventEmitter.emit (events.js:210:5)`
`13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)`
`13 verbose stack     at ChildProcess.emit (events.js:210:5)`
`13 verbose stack     at maybeClose (internal/child_process.js:1023:16)`
`13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:281:5)`
`14 verbose pkgid flood@1.0.0`
`15 verbose cwd /home/flint/flood`
`16 verbose Linux 5.3.13-arch1-1`
`17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"`
`18 verbose node v13.2.0`
`19 verbose npm  v6.12.1`
`20 error code ELIFECYCLE`
`21 error errno 1`
`22 error flood@1.0.0 build: 'node client/scripts/build.js'`
`22 error Exit status 1`
`23 error Failed at the flood@1.0.0 build script.`
`23 error This is probably not a problem with npm. There is likely additional logging output above.`
`24 verbose exit [ 1, true ]`

## Steps to Reproduce
1. Attempt to follow the **Compiling assets and starting the server** section after doing a fresh clone or pulling updates
2. After running **npm run build**, observe the above error output
[2019-11-26T16_57_43_846Z-debug.log](https://github.com/Flood-UI/flood/files/3893186/2019-11-26T16_57_43_846Z-debug.log)

**Comment by mirolm** [comment]
This error only occurs if you run "npm audit fix". If you skip it and run "npm install" and then "npm run build" it completed. succesfully. Before audit fix caused no such issues.

I noticed an error when installing node-sass too. To install okay i needed to run "npm install node-sass" so it installs.

**Comment by mattgorecki** [comment]
I'm running into the same issue.  I was able to install node-sass separately and clear that error, but I'm also getting npm dependency unmet errors on eslint, eslint-plugin-jsx-a11y and eslint-config-react-app.

**Comment by JohnFlowerful** [comment]
```rm -rf /path/to/flood/node_modules``` then ```npm install``` again. If that doesn't work, try ```rm -rf ~/.npm``` as well.

I rebuilt node-sass as well, but I don't think that was required.

**Comment by StealthBadger747** [comment]
I was getting this same error. After following JonFlowerful's tips I wasn't successful at removing the new packages/updates. I am not familiar with JS at all, but I managed to fix the issue. I edited line 2 in ./client/scripts/typed-css-modules-loader.js .
The original line:
`const DtsCreator = require('typed-css-modules');`
My edited version:
`const DtsCreator = require('typed-css-modules').default;`

I was then able to build it successfully with the audit fix.
I'm not sure where or if I should report this.

**Comment by qstyler** [comment]
addition to @JohnFlowerful comment
don't forget to roll `package.json` file back.
