### ISSUE TITLE
TypeError: Cannot read property 'clientGatewayService' of undefined

### ISSUE THREAD

**Issue by FlynnLives** [Flood-UI/flood#863]
Type: Bug Report

- [X] Try to follow the update procedure described in the README and try again before opening this issue.
- [X] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [X] Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

## Your Environment
* Version used: 
  + Version (stable release) v1.0.0
  + Commit ID (development release) commit bb553506a86225811a965563af99bf8e39cc433f (HEAD -> master, origin/master, origin/HEAD)

* Environment name and version:
  + Node.js version v13.8.0
  + npm version 6.13.6
  + Web browser Chrome 79 / Safari 13.0.2 
* Operating System and version: Debian 10 

## Summary
There is a decent chance on a fresh install adding the rtorrent connection type of TCP or UNIX Socket, will cause flood to crash
If it manages to make it past this point there is a 50/50 chance flood will work for a minute and show current loaded torrent statues but shortly after crashes.
If it does not crash on its own, brining up the dialogue to add a torrent file or dropping it into the page causes flood to crash

## Expected Behavior
adds the torrent file to rtorrent and don't crash

## Current Behavior
$ npm start

> flood@1.0.0 start /home/flynn/flood
> node --use_strict  server/bin/start.js

Flood server starting on http://0.0.0.0:3000.

GET /overview 304 3.575 ms - -
GET /static/js/main.ed991fb9.js 304 0.572 ms - -
GET /auth/verify?1582004960810 200 19.495 ms - 55
GET /static/media/Roboto-regular.f84cb1bf.woff2 304 2.817 ms - -
GET /static/media/Roboto-italic.4dcf65b9.woff2 304 2.816 ms - -
GET /static/media/Roboto-700.3b38c16e.woff2 304 2.841 ms - -
GET /static/media/Roboto-500.1afbee5a.woff2 304 2.844 ms - -
GET /favicon.ico 200 4.860 ms - -
GET /api/client/settings 200 4.777 ms - -
GET /api/settings 200 18.252 ms - 71
POST /api/client/connection-test 200 32.440 ms - 20
PATCH /auth/users/flynn 200 5.280 ms - -
GET /api/activity-stream?historySnapshot=fiveMin 200 16.312 ms - -
/home/flynn/flood/server/services/historyService.js:141
    this.services.clientGatewayService
                  ^

TypeError: Cannot read property 'clientGatewayService' of undefined
    at HistoryService.fetchCurrentTransferSummary (/home/flynn/flood/server/services/historyService.js:141:19)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flood@1.0.0 start: `node --use_strict  server/bin/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flood@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/flynn/.npm/_logs/2020-02-18T05_49_26_053Z-debug.log

$ cat /home/flynn/.npm/_logs/2020-02-18T05_49_26_053Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.13.6
3 info using node@v13.8.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle flood@1.0.0~prestart: flood@1.0.0
6 info lifecycle flood@1.0.0~start: flood@1.0.0
7 verbose lifecycle flood@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle flood@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/flynn/flood/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle flood@1.0.0~start: CWD: /home/flynn/flood
10 silly lifecycle flood@1.0.0~start: Args: [ '-c', 'node --use_strict  server/bin/start.js' ]
11 silly lifecycle flood@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle flood@1.0.0~start: Failed to exec start script
13 verbose stack Error: flood@1.0.0 start: `node --use_strict  server/bin/start.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid flood@1.0.0
15 verbose cwd /home/flynn/flood
16 verbose Linux 4.19.0-6-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v13.8.0
19 verbose npm  v6.13.6
20 error code ELIFECYCLE
21 error errno 1
22 error flood@1.0.0 start: `node --use_strict  server/bin/start.js`
22 error Exit status 1
23 error Failed at the flood@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

## Steps to Reproduce

1. npm start
2. add rtorrent connect
3. add torrent

**Comment by Haarolean** [comment]
I keep getting the same exception when using flood behind a proxy.

**Comment by FlynnLives** [comment]
> I keep getting the same exception when using flood behind a proxy.

I get this without using a reverse proxy, did try a reverse proxy with nginx and the issue persisted

**Comment by moooV252** [comment]
Yes, exactly the same problem here. I've even registered an account to leave this commentary.
Previous version of Flood I had (installed a year ago) worked ok.

nodejs: v12.16.2
npm: 6.14.4
Flood latest cloned from git.

Steps to reproduce:
1) Open Flood
2) Register username and password
3) fill in the unix socket path to rtorrent, test it, save it
4) browser resets connection, flood server quits with error.

`Flood server starting on http://127.0.0.1:3000.

GET /overview 304 7.742 ms - -
GET /static/js/main.152fbc43.js 304 1.237 ms - -
GET /auth/verify?1587534901666 200 4.671 ms - 54
GET /api/client/settings 200 12.509 ms - -
GET /api/settings 200 177.811 ms - 2
POST /api/client/connection-test 200 20.622 ms - 20
PATCH /auth/users/test 200 12.030 ms - -
GET /api/activity-stream?historySnapshot=fiveMin 200 14.795 ms - -
/mnt/trash/flood/flood/server/services/historyService.js:141
    this.services.clientGatewayService
                  ^

TypeError: Cannot read property 'clientGatewayService' of undefined
    at HistoryService.fetchCurrentTransferSummary (/mnt/tr/flood/flood/server/services/historyService.js:141:19)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)`

Maybe there's a commit which has affected it to have this behaviour? A year ago it worked ok, but had other bugs.

**Comment by christianhassler** [comment]
not running it behind a reverse proxy fixed it for me. still don't know what it is about the reverse proxy that's causing problems but i assume it's something to do with CGI. fwiw i was using lighttpd on arch linux. idk if it helps, but this was my config (which again, doesn't work):
```
$HTTP["host"] == "torrent.mydomain.tld" {
        proxy.server = ( "" => (
        ( "host" => "127.0.0.1", "port" => 3000 )
        ))
}
```

**Comment by aptkingston** [comment]
Same issue here running a reverse proxy (nginx in my case).

**Comment by JMarkin** [comment]
I fixed it by remove [line](https://github.com/Flood-UI/flood/blob/bb553506a86225811a965563af99bf8e39cc433f/server/services/BaseService.js#L18)

**Comment by moooV252** [comment]
Thanks a lot, that really worked!
