### ISSUE TITLE
Unable to install flood on FreeBSD 12.2-RELEASE-p3

### ISSUE THREAD

**Issue by jakobbg** [Flood-UI/flood#891]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.
- [x] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [x] Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

## Your Environment
* Version used:
  + Version v1.0.0
  + Commit ID bb553506a86225811a965563af99bf8e39cc433f
* Environment name and version:
  + Node.js version v15.8.0
  + npm version 6.14.8
  + Web browser: Chrome MacOS latest
* Operating System and version: FreeBSD 12.2-RELEASE-p3

## Summary
Install fails:

```
➜  flood git:(master) npm install

> argon2@0.24.1 install /usr/home/jakobbg/.local/flood/node_modules/argon2
> node-gyp-build

gyp ERR! configure error
gyp ERR! stack Error: Command failed: /usr/local/bin/python3.9 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:327:12)
gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
gyp ERR! System FreeBSD 12.2-RELEASE-p3
gyp ERR! command "/usr/local/bin/node" "/usr/home/jakobbg/.local/flood/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/jakobbg/.local/flood/node_modules/argon2
gyp ERR! node -v v15.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@2.1.0 requires a peer of babel-eslint@^7.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@2.1.0 requires a peer of eslint@^4.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@2.1.0 requires a peer of eslint-plugin-jsx-a11y@^5.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"freebsd","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.24.1 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the argon2@0.24.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jakobbg/.npm/_logs/2021-02-14T23_06_27_086Z-debug.log
```

Last parts from logfile:

```
749 warn acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
750 warn eslint-config-react-app@2.1.0 requires a peer of babel-eslint@^7.2.3 but none is installed. You must install peer dependencies yourself.
751 warn eslint-config-react-app@2.1.0 requires a peer of eslint@^4.1.1 but none is installed. You must install peer dependencies yourself.
752 warn eslint-config-react-app@2.1.0 requires a peer of eslint-plugin-jsx-a11y@^5.1.1 but none is installed. You must install peer dependencies yourself.
753 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
754 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"freebsd","arch":"x64"})
755 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
755 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
755 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   freebsd
755 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
756 verbose stack Error: argon2@0.24.1 install: `node-gyp-build`
756 verbose stack Exit status 1
756 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
756 verbose stack     at EventEmitter.emit (node:events:378:20)
756 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
756 verbose stack     at ChildProcess.emit (node:events:378:20)
756 verbose stack     at maybeClose (node:internal/child_process:1067:16)
756 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
757 verbose pkgid argon2@0.24.1
758 verbose cwd /usr/home/jakobbg/.local/flood
759 verbose FreeBSD 12.2-RELEASE-p3
760 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
761 verbose node v15.8.0
762 verbose npm  v6.14.8
763 error code ELIFECYCLE
764 error errno 1
765 error argon2@0.24.1 install: `node-gyp-build`
765 error Exit status 1
766 error Failed at the argon2@0.24.1 install script.
766 error This is probably not a problem with npm. There is likely additional logging output above.
767 verbose exit [ 1, true ]
```

## Expected Behavior
npm install succeeding

## Current Behavior
npm err :-)

## Context
Trying to get flood up and running on FreeBSD 12.2-RELEASE-p3. If possible :-). Not having python 2, only /usr/local/bin/python3.9, being Python 3.9.1.

**Comment by thnee** [comment]
This problem is not specific to 12.2, an I suspect not specific to FreeBSD either (although I haven't tried running flood on Linux). All you need to do is specify the correct version of python.

I had a solution for this, that used to work, which was this:

```
PYTHON=/usr/local/bin/python2.7 npm install
```

However, this recently stopped working, no idea why (welcome to javascript), but apparently this works now instead:

```
npm install --python=/usr/local/bin/python2.7
```

(Obviously you need to have python2 installed, which is gonna be `pkg install python27` on FreeBSD 12).

**Comment by thnee** [comment]
And I also want to add that it's a bit worrying to see this kind of issue in 2021. Python 2 is EOL since over a year ago, January 1 2020, so I really wonder why this project depends on it.

But I don't know anything about it, or why it even needs any python at all. Just hope there is a plan in place to at least upgrade to python 3 sometime soon.

**Comment by sa7mon** [comment]
I also ran into this trying to build Flood inside a FreeBSD 12.2 jail.  The culprit seems to be the fact that some dependencies depend on an older version of `node-gyp` that only supports Python2. I haven't tracked it down, but the version of `node-gyp` that started supporting Python3 is somewhere around 7.1

There are at least 2 Flood dependencies that require this old version of `node-gyp`: `argon2` and `node-sass`. These changes to `package.json` got `npm install` to succeed, but may break things down the line (I have yet to fully investigate the effects):

**package.json**

```diff
diff --git a/package.json b/package.json
index 6d2681b..7614627 100644
--- a/package.json
+++ b/package.json
@@ -32,7 +32,7 @@
     "@types/react-dom": "^16.9.4",
     "@types/react-intl": "^2.3.18",
     "@typescript-eslint/parser": "^1.13.0",
-    "argon2": "^0.24.1",
+    "argon2": "^0.27.2",
     "autoprefixer": "^8.6.5",
     "axios": "^0.19.0",
     "babel-eslint": "^10.0.3",
@@ -65,7 +65,7 @@
     "multer": "^1.4.2",
     "mv": "^2.1.1",
     "nedb": "^1.8.0",
-    "node-sass": "^4.13.0",
+    "node-sass": "^5.0.0",
     "object-assign": "4.1.1",
     "ospath": "^1.2.2",
     "pascal-case": "^2.0.1",

```

**Comment by jakobbg** [comment]
Thanks. The other fork worked perfectly.
